site: serverlist.games
username: delphicraft
password: Ru4$NQtk&k#ckU5
vote_name: obzidi4n
url_login: https://serverlist.games/en/login
url_bump: https://serverlist.games/en/dashboard
url_vote: https://serverlist.games/en/vote/2365