site: mc-servers.com
username: delphicraft
password: 9#dGHJqdu7Yg2ep
vote_name: obzidi4n
url_login: https://mc-servers.com/login
url_bump: https://mc-servers.com/my_servers?bump=3655
url_vote: https://mc-servers.com/mcvote/3655/