site:
  name: planetminecraft.com
  url: https://www.planetminecraft.com
  username: obz@delphicraft.net
  password: cR38t6qMb$26
  page: https://www.planetminecraft.com/account/manage/servers/4442719/#tab_log