site: minecraft-server.net
username: delphicraft
password: UV7tysxhaP9uf9z
vote_name: obzidi4n
url_bump: https://minecraft-server.net/user_cpl/
url_vote: https://minecraft-server.net/vote/delphicraft/
url_login: https://minecraft-server.net/user_cpl/