sites:
#   name: discordservers.com
#   url: https://discordservers.com
#   login: obz@delphicraft.net
#   password: mRhDx2KIeQUAU8%4
#   page: https://discordservers.com/panel/210536719844376576/bump
#   name: minecraft-server.net
#   url: https://minecraft-server.net
#   login: delphicraft
#   password: cR38t6qMb$26
#   page: https://minecraft-server.net/user_cpl/
  name: planetminecraft.com
  url: https://www.planetminecraft.com
  username: obz@delphicraft.net
  password: cR38t6qMb$26
  page: https://www.planetminecraft.com/account/manage/servers/4442719/#tab_log
#   name: serverlist.games
#   url: https://serverlist.games
#   login: obz@delphicraft.net
#   password: cR38t6qMb$26
#   page: https://serverlist.games/dashboard
#   name: serverpact.com
#   url: https://www.serverpact.com
#   login: delphicraft
#   password: cR38t6qMb$26
#   page: https://www.serverpact.com/minecraft-server-timeline.htm
#   name: topg.org
#   url: https://topg.org
#   login: obz@delphicraft.net
#   password: cR38t6qMb$26
#   page: https://topg.org/edit_updates-518675
#   name: mc-servers.com
#   url: https://mc-servers.com
#   login: delphicraft
#   password: cR38t6qMb$26
#   page: https://mc-servers.com/my_servers?bump=3655